apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreact-app-deployment
  labels:
    app: myreact-app
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: myreact-app
  template:
    metadata:
      labels:
        app: myreact-app
    spec:
      containers:
      - name: myreact-app
        image: bayeracr.azurecr.io/bayer-myreactapp # Replace with your Docker image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myreact-app-service
spec:
  selector:
    app: myreact-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 3000
  type: NodePort
